### ISSUE TITLE
Left corner no click

### ISSUE THREAD

**Issue by Acroexist69** [samliew/SO-mod-userscripts#103]
**Describe the bug**
Please state which userscript is causing the issue, and a description of the bug.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by makyen** [comment]
The contents of the opening comment here are just the default contents of the New Bug template for this repository. If you have an actual issue, then you are expected to change those contents in order to describe the bug. The only thing here which isn't stock text is the title of "Left corner no click", which is insufficient for anyone to identify what issue you are really having.

In other words, this issue should be closed.
