### ISSUE TITLE
MMH: Big padding on the /admin page

### ISSUE THREAD

**Issue by kamil-tekiela** [samliew/SO-mod-userscripts#150]
**Describe the bug**
The mod message helper recent update introduced extra whitespace to the mod flag table https://stackoverflow.com/admin. 

**To Reproduce**
1. Go to to /admin
2. See the whitespace

**Expected behavior**
No whitespace as is in the vanilla. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6583064/197892175-bc56354b-5a74-45b2-9e54-e5ea162b89ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 106

@makyen CC

**Comment by makyen** [comment]
Just FYI: This isn't the result of changes I made. It existed in the version prior to my recent PRed changes.

Interestingly, it doesn't happen in my personal version, which has a few more changes. I didn't include those in my PR, because most of them are CSS changes, and a bit of HTML, but I made them long enough ago such that I wasn't confident in describing the exact impact, the reason for the changes, and verifying that there wasn't an issue (mostly because I'm unsure as to what the intent was with some of the existing CSS).

I'll PR another change which will at least resolve this specific issue on the /admin page.
